import { PrismaClient, ItemType, ItemRarity } from '@prisma/client';

export async function seedItems(db: PrismaClient) {
  const items = [
    // Weapons
    {
      name: 'Street Brawler',
      description: 'A basic but reliable melee weapon for close combat',
      type: ItemType.WEAPON,
      rarity: ItemRarity.COMMON,
      stats: { damage: 15, speed: 1.2, range: 'melee' },
      effects: {},
      baseValue: 50,
      tradeable: true,
      stackable: false,
    },
    {
      name: 'Plasma Cutter',
      description: 'Advanced energy blade that slices through armor',
      type: ItemType.WEAPON,
      rarity: ItemRarity.RARE,
      stats: { damage: 45, speed: 1.0, range: 'melee', armorPen: 15 },
      effects: { burn: { chance: 0.2, damage: 5 } },
      baseValue: 1500,
      tradeable: true,
      stackable: false,
    },
    {
      name: 'Neon Katana',
      description: 'Legendary blade infused with neon energy',
      type: ItemType.WEAPON,
      rarity: ItemRarity.LEGENDARY,
      stats: { damage: 80, speed: 1.5, range: 'melee', crit: 25 },
      effects: { energyBlade: { bonusDamage: 20 } },
      baseValue: 10000,
      tradeable: true,
      stackable: false,
      imageUrl: 'https://example.com/neon-katana.png',
    },

    // Armor
    {
      name: 'Leather Jacket',
      description: 'Basic protection for street fighters',
      type: ItemType.ARMOR,
      rarity: ItemRarity.COMMON,
      stats: { defense: 10, weight: 5 },
      effects: {},
      baseValue: 75,
      tradeable: true,
      stackable: false,
    },
    {
      name: 'Kevlar Vest',
      description: 'Military-grade ballistic protection',
      type: ItemType.ARMOR,
      rarity: ItemRarity.UNCOMMON,
      stats: { defense: 25, weight: 12 },
      effects: { bulletResist: 20 },
      baseValue: 500,
      tradeable: true,
      stackable: false,
    },
    {
      name: 'Exo-Suit',
      description: 'Powered armor with integrated systems',
      type: ItemType.ARMOR,
      rarity: ItemRarity.EPIC,
      stats: { defense: 60, weight: 30, strength: 15 },
      effects: { powerArmor: { damageReduction: 15 } },
      baseValue: 5000,
      tradeable: true,
      stackable: false,
    },

    // Cyberware
    {
      name: 'Neural Processor',
      description: 'Enhances cognitive functions and reaction time',
      type: ItemType.CYBERWARE,
      rarity: ItemRarity.RARE,
      stats: { intelligence: 5, dexterity: 3 },
      effects: { quickhack: { cooldownReduction: 15 } },
      baseValue: 2000,
      tradeable: false,
      stackable: false,
    },
    {
      name: 'Mantis Blades',
      description: 'Retractable arm blades for brutal melee combat',
      type: ItemType.CYBERWARE,
      rarity: ItemRarity.EPIC,
      stats: { damage: 50, speed: 1.8 },
      effects: { bleed: { chance: 0.3, damage: 10 } },
      baseValue: 7500,
      tradeable: false,
      stackable: false,
    },

    // Consumables
    {
      name: 'Health Stim',
      description: 'Instantly restores 50 HP',
      type: ItemType.CONSUMABLE,
      rarity: ItemRarity.COMMON,
      stats: { healing: 50 },
      effects: { instant: true },
      baseValue: 25,
      tradeable: true,
      stackable: true,
      maxStack: 10,
    },
    {
      name: 'Energy Booster',
      description: 'Restores 30 energy and increases speed for 60 seconds',
      type: ItemType.CONSUMABLE,
      rarity: ItemRarity.UNCOMMON,
      stats: { energyRestore: 30, speedBoost: 20 },
      effects: { duration: 60 },
      baseValue: 50,
      tradeable: true,
      stackable: true,
      maxStack: 5,
    },
    {
      name: 'Combat Enhancer',
      description: 'Increases damage by 30% for 5 minutes',
      type: ItemType.CONSUMABLE,
      rarity: ItemRarity.RARE,
      stats: { damageBoost: 30 },
      effects: { duration: 300 },
      baseValue: 200,
      tradeable: true,
      stackable: true,
      maxStack: 3,
    },

    // Materials
    {
      name: 'Scrap Metal',
      description: 'Common crafting material',
      type: ItemType.MATERIAL,
      rarity: ItemRarity.COMMON,
      stats: {},
      effects: {},
      baseValue: 5,
      tradeable: true,
      stackable: true,
      maxStack: 100,
    },
    {
      name: 'Electronics',
      description: 'Salvaged electronic components',
      type: ItemType.MATERIAL,
      rarity: ItemRarity.UNCOMMON,
      stats: {},
      effects: {},
      baseValue: 15,
      tradeable: true,
      stackable: true,
      maxStack: 50,
    },
    {
      name: 'Rare Alloy',
      description: 'High-grade metal for advanced crafting',
      type: ItemType.MATERIAL,
      rarity: ItemRarity.RARE,
      stats: {},
      effects: {},
      baseValue: 100,
      tradeable: true,
      stackable: true,
      maxStack: 25,
    },
    {
      name: 'Quantum Core',
      description: 'Exotic material with quantum properties',
      type: ItemType.MATERIAL,
      rarity: ItemRarity.LEGENDARY,
      stats: {},
      effects: {},
      baseValue: 1000,
      tradeable: true,
      stackable: true,
      maxStack: 10,
    },

    // Vehicles
    {
      name: 'Street Bike',
      description: 'Fast motorcycle for navigating city streets',
      type: ItemType.VEHICLE,
      rarity: ItemRarity.UNCOMMON,
      stats: { speed: 120, handling: 80 },
      effects: {},
      baseValue: 5000,
      tradeable: true,
      stackable: false,
    },
    {
      name: 'Hover Car',
      description: 'Futuristic vehicle with anti-grav technology',
      type: ItemType.VEHICLE,
      rarity: ItemRarity.EPIC,
      stats: { speed: 150, handling: 95, armor: 20 },
      effects: { hover: true },
      baseValue: 25000,
      tradeable: true,
      stackable: false,
    },
  ];

  // Upsert items (create or update)
  for (const item of items) {
    await db.item.upsert({
      where: { id: `seed_${item.name.toLowerCase().replace(/\s+/g, '_')}` },
      create: { id: `seed_${item.name.toLowerCase().replace(/\s+/g, '_')}`, ...item },
      update: item,
    });
  }

  console.log(`  Created ${items.length} items`);
}
