[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --workspace=apps/backend"]

[phases.build]
cmds = ["npm run build --workspace=apps/backend"]

[start]
cmd = "npm start --workspace=apps/backend"
