plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\heyzo\\clawd\\projects\\darkcity\\deploy"
publishOrigin = "default"
base = "C:\\Users\\heyzo\\clawd\\projects\\darkcity\\deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]